# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datehired',
            field=models.DateField(default=datetime.datetime(2016, 7, 27, 16, 31, 14, 963997, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
